### PR TITLE
fix skip 'current_time' addition

### LINKED ISSUE #93: overlapping timestamps cause the end time to add up
example:  
if we set 'violence' and 'verbal abuse' to 'skip', the following cnsr file should skip from 00:00:00,000 to 00:00:010,000 .
cnsr_file:

> 00:00:00,000 - 00:00:10,000; 1
> 00:00:00,000 - 00:00:10,000; 2

instead, the video skips from  00:00:00,000 to 00:00:020,000

### PR DESCRIPTION
**Pull request by Gal-Tch**

### CODE REVIEW

**Review by ophirhan — CHANGES_REQUESTED** [review]
Eyal and I disscussed this and we have a solution which lets us keep the desired behavior while fixing this bug.
We want to skip as if the skip section was "cut out of the tape".
I tried detailing it here but it's too complicated I'll explain it to you tomorrow. :-P

File: intf/cnsr_intf.lua [hunk 1]
```diff
@@ -196,16 +196,15 @@ end
...
 --]]
 function skip(skip_start, skip_end)
 	prev_time = current_time
-	local skip_length = skip_end - skip_start
 	if forward then
-		current_time = math.min(current_time + skip_length + SKIP_SAFETY, vlc.input.item():duration() * MS_IN_SEC) --think if we want to!
+		current_time = math.min(skip_end + SKIP_SAFETY, vlc.input.item():duration() * MS_IN_SEC) --think if we want to!
 	else -- we went back in time, cut the duration of skip tag from timeline
-		current_time = math.max(current_time - skip_length, 0)
+		current_time = math.max(skip_start, 0)
```
Comment (ophirhan) [inline intf/cnsr_intf.lua]: skipping to skip_start is the same as skipping to skip_end
skip to skip_start -5,000,000 microseconds

**Review by ophirhan — APPROVED** [review]
