### PR TITLE
fixed my issue that the hide just made the screen a bit darker

### LINKED ISSUE #120: hide option seems to just make the screen darker but not fully dark.
I belive I am the only one in the group experiencing this, but on my computer the screen just seems to be a bit darker.
without hide filter:
image
with hide filter:
image

### PR DESCRIPTION
**Pull request by alonShevach**

### CODE REVIEW

File: intf/cnsr_intf.lua [hunk 1]
```diff
@@ -131,6 +131,9 @@ actions.hide.update= function() check_deactivate(actions.hide) end
 function actions.hide.activate()
 	actions.hide.hide_filter = vlc.object.vout()
 	vlc.var.create(actions.hide.hide_filter, "contrast", 0)
+	vlc.var.create(actions.hide.hide_filter, "brightness", 0)
+	vlc.var.create(actions.hide.hide_filter, "saturation", 0)
+	vlc.var.create(actions.hide.hide_filter, "gamma", 0)
```
Comment (ophirhan) [inline intf/cnsr_intf.lua:136]: Did you really have to change **all** of these values?

Comment (alonShevach) [reply intf/cnsr_intf.lua:136]: the gamma doesn't have to be changed, the others needs to be changed(if one of them is on you might see something).
my thought with gamma was that it's better safe than sorry, so just in case it will change, we should cover this.

**Review by ophirhan — APPROVED** [review]
